name: hackaton_app
description: "Sistema de Monitoreo en Tiempo Real del Transporte Público - Hackathon Nicaragua 2025"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core (ya lo tienes)
  firebase_core: ^4.1.0
  
  # Firebase productos esenciales
  cloud_firestore: ^6.0.1          # Base de datos
  firebase_auth: ^5.2.0            # Autenticación (¡IMPORTANTE!)
  firebase_storage: ^13.0.1        # Almacenamiento
  firebase_messaging: ^14.7.0      # Notificaciones push (para alertas)
  
  # Estado y Gestión de Datos
  flutter_bloc: ^8.1.3             # BLoC para gestión de estado
  equatable: ^2.0.5                # Para comparar objetos
  provider: ^6.1.1                 # Provider para inyección de dependencias
  
  # Navegación
  go_router: ^13.0.1               # Navegación declarativa (recomendado)
  # O usar: auto_route: ^7.0.0     # Alternativa potente
  
  # Mapas y Geolocalización
  google_maps_flutter: ^2.5.0      # Mapas de Google (mejor para transporte)
  geolocator: ^11.0.0              # Geolocalización
  geocoding: ^2.1.1                # Geocodificación (direcciones → coordenadas)
  
  # UI y Utilidades
  cupertino_icons: ^1.0.8
  flutter_localizations:           # Internacionalización
    sdk: flutter
  intl: ^0.19.0                    # Formato de fechas y números
  shared_preferences: ^2.2.2       # Almacenamiento local
  image_picker: ^1.2.0
  uuid: ^4.5.1
  flutter_dotenv: ^5.1.0           # Variables de entorno (para API keys)
  
  # HTTP y Conexiones
  http: ^1.2.0                     # Cliente HTTP
  connectivity_plus: ^5.0.0        # Verificar conectividad

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8             # Para code generation
  mockito: ^5.4.4                  # Para testing (mocks)

flutter:
  uses-material-design: true
  
  # Assets (agregaremos después)
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Fonts (agregaremos después)
  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #       - asset: assets/fonts/OpenSans-Bold.ttf
  #         weight: 700

  # Google Maps API key (para Android)
  # --- AGREGAR EN android/app/src/main/AndroidManifest.xml ---
  # <meta-data
  #   android:name="com.google.android.geo.API_KEY"
  #   android:value="TU_API_KEY"/>